#!/bin/bash

# this script installs the system and python depdencies for fondz in /opt/fondz
# so you will need to run it with sudo. It is specific to Ubuntu but you should
# be able to riff off of it to install on other operating systems like OS X.

echo "- installing system level dependencies"
apt-get install --yes libreoffice python-virtualenv virtualenvwrapper python-pip mercurial default-jdk ant libimage-exiftool-perl gcc

if [ -z $FONDZ_HOME ]; then 
    FONDZ_HOME=/opt/fondz
fi
if [ ! -d $FONDZ_HOME ]; then
    echo "- creating $FONDZ_HOME"
    mkdir $FONDZ_HOME
fi

MALLET_HOME="$FONDZ_HOME/mallet"
if [ ! -d "$MALLET_HOME" ]; then
    echo "- installing mallet in $MALLET_HOME"
    hg clone http://hg-iesl.cs.umass.edu/hg/mallet >/dev/null
    cd mallet ; ant >/dev/null ; cd ..
    mv mallet "$MALLET_HOME"
fi

FIDO_HOME="$FONDZ_HOME/fido"
if [ ! -d "$FIDO_HOME" ]; then
    echo "- installing fido in $FIDO_HOME"
    wget --quiet https://github.com/openplanets/fido/archive/1.3.1-70.tar.gz
    tar xfz 1.3.1-70.tar.gz
    mv fido-1.3.1-70 "$FIDO_HOME"
    rm 1.3.1-70.tar.gz
fi

echo "- updating PATH in $HOME/.profile"
echo "export PATH=$MALLET_HOME/bin:$FIDO_HOME/fido:\$PATH" >> $HOME/.profile
source "$HOME/.profile"

echo "- installing python dependencies"
pip install -r requirements.txt

echo "- installing fondz"
python setup.py install

# this artifact of the setup.py install can interfere with running tests later
if [ -d "fondz.egg-info" ]; then
    rm -rf fondz.egg-info
fi

echo "finished installation!"
echo "you should be able to run fondz from the command line now"
